spring.application.name=proyecto
server.port=9093

spring.datasource.url=jdbc:mysql://localhost:3306/pathFinder
spring.datasource.username=PathFinder
spring.datasource.password=PathFinder

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
